// <auto-generated />
using System;
using BotForge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotForge.Persistence.Migrations
{
    [DbContext(typeof(BotForgeDbContext))]
    partial class BotForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BotForge.Persistence.Models.BotRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WelcomeMessageKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BotRoles");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.BotUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Discriminator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocale")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlatformUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLocale")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username", "Discriminator")
                        .IsUnique();

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.UserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateData")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStates");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.BotUser", b =>
                {
                    b.HasOne("BotForge.Persistence.Models.BotRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.UserState", b =>
                {
                    b.HasOne("BotForge.Persistence.Models.BotUser", "User")
                        .WithOne("State")
                        .HasForeignKey("BotForge.Persistence.Models.UserState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.BotRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BotForge.Persistence.Models.BotUser", b =>
                {
                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}

