//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotForge.Analyzers {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotForge.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotForge state attributes must be declared correctly.
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State attribute usage requires correction.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BotForge FSM Analyzer.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; has incorrect signature for [Menu]. Expected: (a)sync (StateResult|Task&lt;StateResult&gt;) Method(SelectionStateContext [, CancellationToken])..
        /// </summary>
        internal static string FSM001Description {
            get {
                return ResourceManager.GetString("FSM001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu state method signature.
        /// </summary>
        internal static string FSM001Title {
            get {
                return ResourceManager.GetString("FSM001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; has incorrect signature for [Prompt&lt;T&gt;]. Expected: (a)sync (StateResult|Task&lt;StateResult&gt;) Method(PromptStateContext&lt;T&gt; [, CancellationToken])..
        /// </summary>
        internal static string FSM002Description {
            get {
                return ResourceManager.GetString("FSM002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt state method signature.
        /// </summary>
        internal static string FSM002Title {
            get {
                return ResourceManager.GetString("FSM002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generic argument of [Prompt&lt;{0}&gt;] does not match method parameter PromptStateContext&lt;{1}&gt;.
        /// </summary>
        internal static string FSM003Description {
            get {
                return ResourceManager.GetString("FSM003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt state generic mismatch.
        /// </summary>
        internal static string FSM003Title {
            get {
                return ResourceManager.GetString("FSM003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [MenuItem] or [MenuRow] used on method &apos;{0}&apos; without [Menu] or [CustomState].
        /// </summary>
        internal static string FSM004Description {
            get {
                return ResourceManager.GetString("FSM004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MenuItem or MenuRow without Menu/CustomState.
        /// </summary>
        internal static string FSM004Title {
            get {
                return ResourceManager.GetString("FSM004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MenuItem or MenuRow label &apos;{0}&apos; is not a public static readonly ButtonLabel member of a class marked with [LabelStorage].
        /// </summary>
        internal static string FSM005Description {
            get {
                return ResourceManager.GetString("FSM005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MenuItem or MenuRow label not found.
        /// </summary>
        internal static string FSM005Title {
            get {
                return ResourceManager.GetString("FSM005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Localization key &apos;{0}&apos; not found in project resources or string members.
        /// </summary>
        internal static string FSM006Description {
            get {
                return ResourceManager.GetString("FSM006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Localization key not found.
        /// </summary>
        internal static string FSM006Title {
            get {
                return ResourceManager.GetString("FSM006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nullability mismatch between attribute generic argument and method parameter: &apos;{0}&apos; vs &apos;{1}&apos;.
        /// </summary>
        internal static string FSM007Description {
            get {
                return ResourceManager.GetString("FSM007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nullability mismatch.
        /// </summary>
        internal static string FSM007Title {
            get {
                return ResourceManager.GetString("FSM007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard instruction [{0}] is used on method {1} without [Menu] or [CustomState].
        /// </summary>
        internal static string FSM008Description {
            get {
                return ResourceManager.GetString("FSM008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard instruction without Menu/CustomState.
        /// </summary>
        internal static string FSM008Title {
            get {
                return ResourceManager.GetString("FSM008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; has incorrect signature for [ModelPrompt&lt;T&gt;]. Expected: (a)sync (StateResult|Task&lt;StateResult&gt;) Method(ModelPromptContext&lt;T&gt; [, CancellationToken])..
        /// </summary>
        internal static string FSM009Description {
            get {
                return ResourceManager.GetString("FSM009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ModelPrompt state method signature.
        /// </summary>
        internal static string FSM009Title {
            get {
                return ResourceManager.GetString("FSM009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; has incorrect signature for [CustomState]. Expected: (a)sync (StateResult|Task&lt;StateResult&gt;) Method(ModuleStateContext [, CancellationToken])..
        /// </summary>
        internal static string FSM010Description {
            get {
                return ResourceManager.GetString("FSM010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CustomState method signature.
        /// </summary>
        internal static string FSM010Title {
            get {
                return ResourceManager.GetString("FSM010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generic argument of [ModelPrompt&lt;{0}&gt;] does not match method parameter ModelPromptContext&lt;{1}&gt;.
        /// </summary>
        internal static string FSM011Description {
            get {
                return ResourceManager.GetString("FSM011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ModelPrompt state generic mismatch.
        /// </summary>
        internal static string FSM011Title {
            get {
                return ResourceManager.GetString("FSM011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider adding resource files for localization to support keys like &apos;{0}&apos;.
        /// </summary>
        internal static string FSM012Description {
            get {
                return ResourceManager.GetString("FSM012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing resource files.
        /// </summary>
        internal static string FSM012Title {
            get {
                return ResourceManager.GetString("FSM012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider adding a class with [LabelStorage] attribute to define button labels.
        /// </summary>
        internal static string FSM013Description {
            get {
                return ResourceManager.GetString("FSM013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing label storage.
        /// </summary>
        internal static string FSM013Title {
            get {
                return ResourceManager.GetString("FSM013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method &apos;{0}&apos; has multiple state attributes. Only one of [Menu], [Prompt&lt;T&gt;], [ModelPrompt&lt;T&gt;] or [CustomState] should be used.
        /// </summary>
        internal static string FSM014Description {
            get {
                return ResourceManager.GetString("FSM014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple state attributes.
        /// </summary>
        internal static string FSM014Title {
            get {
                return ResourceManager.GetString("FSM014Title", resourceCulture);
            }
        }
    }
}
