//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotForge.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotForge.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu state attributes must be declared correctly.
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need this?.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu analyzer.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; has incorrect signature for [MenuState]. Expected: public instance Task&lt;StateResult&gt; Method(ModuleStateContext)..
        /// </summary>
        internal static string FSM001Description {
            get {
                return ResourceManager.GetString("FSM001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu state method signature.
        /// </summary>
        internal static string FSM001Title {
            get {
                return ResourceManager.GetString("FSM001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; has incorrect signature for [PromptState&lt;T&gt;]. Expected: public instance Task&lt;StateResult&gt; Method(PromptStateContext&lt;T&gt;)..
        /// </summary>
        internal static string FSM002Description {
            get {
                return ResourceManager.GetString("FSM002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt state method signature.
        /// </summary>
        internal static string FSM002Title {
            get {
                return ResourceManager.GetString("FSM002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic argument of [PromptState&lt;{0}&gt;] does not match method parameter PromptStateContext&lt;{1}&gt;.
        /// </summary>
        internal static string FSM003Description {
            get {
                return ResourceManager.GetString("FSM003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt state generic mismatch.
        /// </summary>
        internal static string FSM003Title {
            get {
                return ResourceManager.GetString("FSM003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MenuItem] used on method &apos;{0}&apos; without [MenuState].
        /// </summary>
        internal static string FSM004Description {
            get {
                return ResourceManager.GetString("FSM004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem without MenuState.
        /// </summary>
        internal static string FSM004Title {
            get {
                return ResourceManager.GetString("FSM004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem label &apos;{0}&apos; is not a public static readonly ButtonLabel member of a class marked with [LabelsStorage].
        /// </summary>
        internal static string FSM005Description {
            get {
                return ResourceManager.GetString("FSM005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem label not found.
        /// </summary>
        internal static string FSM005Title {
            get {
                return ResourceManager.GetString("FSM005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization key &apos;{0}&apos; not found in project resources or string members.
        /// </summary>
        internal static string FSM006Description {
            get {
                return ResourceManager.GetString("FSM006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization key not found.
        /// </summary>
        internal static string FSM006Title {
            get {
                return ResourceManager.GetString("FSM006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullability mismatch between attribute generic argument and method parameter: &apos;{0}&apos; vs &apos;{1}&apos;.
        /// </summary>
        internal static string FSM007Description {
            get {
                return ResourceManager.GetString("FSM007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullability mismatch.
        /// </summary>
        internal static string FSM007Title {
            get {
                return ResourceManager.GetString("FSM007Title", resourceCulture);
            }
        }
    }
}
