# TODO: uncomment when projects are ready for publishing
# name: Build and Pack
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: 8.0.x
#       - run: dotnet restore BotForge.sln
#       - run: dotnet build BotForge.sln -c Release --no-restore
#       - run: dotnet pack src/BotForge.Core/BotForge.Core.csproj -c Release -o ./artifacts
